#!/usr/bin/env python3 

from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP

# Generate a public/private key pair
key = RSA.generate(2048)

# Save the private key to a file
private_key = key.export_key()
with open('private_key.pem', 'wb') as f:
    f.write(private_key)

# Save the public key to a file
public_key = key.publickey().export_key()
with open('public_key.pem', 'wb') as f:
    f.write(public_key)

# Encrypt a message using the public key
message = input('Enter a secret Message: ').encode()
cipher = PKCS1_OAEP.new(RSA.import_key(public_key))
encrypted_message = cipher.encrypt(message)

# Save the encrypted message to a file
with open('encrypted_message.hex', 'w') as f:
    f.write(encrypted_message.hex())